# Generated by Django 4.1 on 2023-01-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('discription', models.TextField(max_length=150)),
            ],
        ),
    ]
