# Generated by Django 4.1 on 2022-12-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_mark_maths_fees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fees',
        ),
    ]
